local_backend: true

backend:
  name: git-gateway
  repo: Shekey/astro-starter
  branch: main
  squash_merges: true

display_url: https://hugo-template.netlify.app/
logo_url: https://www.google.com/url?sa=i&url=https%3A%2F%2Ficonduck.com%2Ficons%2F77028%2Fnetlify&psig=AOvVaw1mOQj30C5NcNlx8cAerHIK&ust=1723030327886000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCLC5_qai4IcDFQAAAAAdAAAAABAE
media_folder: public/media/uploads
public_folder: /media/uploads

slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }