export const GLOBAL_ENVS = {
  isProd: !!import.meta.env.PROD,
  HYGRAPH_ENDPOINT: import.meta.env.HYGRAPH_ENDPOINT,
  HYGRAPH_SECURE_TOKEN_PUBLISHED: import.meta.env.HYGRAPH_SECURE_TOKEN_PUBLISHED,
  HYGRAPH_STALE_IF_ERROR_DURATION: import.meta.env.HYGRAPH_STALE_IF_ERROR_DURATION,
  HYGRAPH_STALE_WHILE_REVALIDATE_DURATION: import.meta.env.HYGRAPH_STALE_WHILE_REVALIDATE_DURATION
};
